title: Hi, I'm Benjamin
description: your-email@example.com
remote_theme: riggraz/no-style-please
plugins:
  - jekyll-remote-theme
baseurl: /aboutme/
url: https://lankypaps.github.io
domain: lankypaps.github.io
