title: Hi, I'm Ben
description: mills.ben97@gmail.com 
remote_theme: riggraz/no-style-please
plugins:
  - jekyll-remote-theme
baseurl: /aboutme/
url: https://lankypaps.github.io
domain: lankypaps.github.io
